### PR TITLE
Fix for Oracle insert many

### LINKED ISSUE #192: OracleCompiler generates invalid multiple row insert
Given the query
```cs
db.Query(string table).AsInsert(IEnumerable<string> columns, IEnumerable<IEnumerable<object>> valuesCollection, bool returnId = false);
```
Compiles to invalid sql for oracle
```sql
INSERT INTO "mtable" ("one", "two") VALUES (3348, 0), (3348, 1), (3348, 2)
```

Implement using [from dual union all](https://stackoverflow.com/questions/39576/best-way-to-do-multi-row-insert-in-oracle).

### PR DESCRIPTION
**Pull request by mathijs-dumon**
This is a replacement PR for this older branch: [issue-192](https://github.com/sqlkata/querybuilder/tree/issue-192)
I compared the test case that was in the old branch, my tests are equivalent.

The generated SQL is slightly different, (INSERT ALL vs UNION ALL) but functionally equivalent. The INSERT ALL approach is more in line with what other dialects do.

This fixes #192

### CODE REVIEW

File: QueryBuilder/Compilers/Compiler.cs [hunk 1]
```diff
@@ -17,6 +17,11 @@ public partial class Compiler
         protected virtual string LastId { get; set; } = "";
         protected virtual string EscapeCharacter { get; set; } = "\\";
 
+
+        protected virtual string SingleInsertStartClause { get; set; } = "INSERT INTO";
```
Comment (ahmad-moussawi) [inline QueryBuilder/Compilers/Compiler.cs:21]: I think this is the case for Oracle only, I prefer removing it from the global compiler, unless it's really needed

**Comment by hcsatoshiwatanabe** [comment]
@mattewre @ahmad-moussawi 
これ(#192)解決されると、非常に嬉しいです。
よろしくです。

**Comment by andrewhosack** [comment]
Hey Ahmad, I love your package and it's working great for me so far. I found this Oracle INSERT MANY issue while working with this compiler in particular and it looks like this merge is going to fix the issue. I was wondering if there is any timeline on the next release for SqlKata, that will include this merged Oracle Compiler change! Thank you!
